config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :posts
  get '/about', to: 'home#about'
  get '/help', to: 'home#help'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :image
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    if current_user.nil?
      redirect_to root_path
    else
      @post = current_user.posts.build
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      
      flash[:success] = "投稿完了!!"
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/about.html.erb
<h1>About</h1>
<p>概要を記述しましょう！</p>

app/views/home/help.html.erb
<h1>Help</h1>
<p>ヘルプページの内容を記述しましょう！</p>

app/views/home/index.html.erb
<h1>Post App</h1>
<%= link_to "投稿一覧ページへ", posts_path, class: 'btn btn-info' %>

app/views/layouts/_footer.html.erb
<footer class='fixed-bottom navbar-dark bg-dark row'>
  <small class='col align-self-end'>
    Sample Application by Sugihara
  </small>
  <ul class='nav float-right'>
    <li class='nav-item'><%= link_to 'About', about_path, class: 'nav-link' %></li>
    <li class='nav-item'><%= link_to 'Help', help_path, class: 'nav-link' %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-dark bg-dark sticky-top'>
  <%= link_to 'Top', root_path, class: 'navbar-brand' %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarNavDropdown'>
    <ul class='navbar-nav'>
      <% if user_signed_in? %>
        <li class='nav-item'><%= link_to 'New Post', new_post_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      <% else %>
        <li class='nav-item'><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
      <li class='nav-item'><%= link_to 'About', about_path, class: 'nav-link' %></li>
      <li class='nav-item'><%= link_to 'Help', help_path, class: 'nav-link' %></li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-primary alert-<%= message_type %>" >
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<ul class='list-group list-group-flush'>
  <% @posts.each do |post| %>
    <%= link_to post.title, post, class: 'list-group-item list-group-item-action' %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_with(model: @post) do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control-file' %>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<h2><%= @post.title %></h2>
<% if @post.image.attached? %>
  <%= image_tag @post.image %>
<% end %>
<%= @post.content %>